services:
    git-server:
        build:
            context: ./server
            args:
                - GIT_USER=git
                - GIT_PASSWORD=${GIT_PASSWORD}
        env_file: .env
        ports:
            - "2222:22"

        volumes:
            - repos:/var/repo
            - www:/var/www

    nginx:
        image: nginx:alpine
        depends_on:
            - git-server
        ports:
            - "8080:80" # Public HTTP
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - www:/var/www

    ngrok:
      image: ngrok/ngrok:latest
      command:
        - "http"
        - "http://host.docker.internal:8080"
      environment:
        NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
      ports:
        - 4040:4040

volumes:
    repos:
    www:
